version: ~> 1.0
language: generic
os: linux
dist: bionic
jobs:
  include:
  - name: "GIFT COPR builds on Fedora 31 (Docker) with Python 3.7"
    env: FEDORA_VERSION="31"
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "GIFT COPR builds on Fedora 32 (Docker) with Python 3.8"
    env: FEDORA_VERSION="32"
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: "GIFT PPA builds on Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: UBUNTU_VERSION="18.04"
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "GIFT PPA builds on Ubuntu Focal (20.04) (Docker) with Python 3.8"
    env: UBUNTU_VERSION="20.04"
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: "Source on Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: [TARGET="gitsource", UBUNTU_VERSION="18.04"]
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Source on Ubuntu Focal (20.04) (Docker) with Python 3.8"
    env: [TARGET="gitsource", UBUNTU_VERSION="20.04"]
    group: edge
    language: python
    python: 3.8
    services:
    - docker
  - name: "Source on MacOS 10.14 with Python 3.8 (tox)"
    env: [TARGET="gitsource", TOXENV="py38"]
    os: osx
    osx_image: xcode11
  - name: "Pylint on Ubuntu Bionic (18.04) with Python 3.6"
    env: [TARGET="pylint3", UBUNTU_VERSION="18.04"]
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Docker Hub builds on Ubuntu Bionic (18.04)"
    env: TARGET="dockerhub"
    group: edge
    services:
    - docker
install:
- ./config/travis/install.sh
script:
- ./config/travis/run_with_timeout.sh 45 ./config/travis/runtests.sh
